import { useEffect, useRef, useState } from 'react';
import { ChatMessage } from '../../hooks/useServerText';
import { colors } from '../../../../theme/colors';

interface TranscriptionPanelProps {
  messages: ChatMessage[];
}

const TranscriptionPanel: React.FC<TranscriptionPanelProps> = ({ messages }) => {
  // Track expanded reference boxes by message ID
  const [expandedRefs, setExpandedRefs] = useState<Set<string>>(new Set());
  const [showDisclaimer, setShowDisclaimer] = useState(false);
  const scrollContainerRef = useRef<HTMLDivElement | null>(null);
  const bottomRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    const container = scrollContainerRef.current;
    const bottom = bottomRef.current;
    if (!container || !bottom) return;

    // Only auto-scroll if user is already near the bottom
    const distanceFromBottom =
      container.scrollHeight - container.scrollTop - container.clientHeight;

    if (distanceFromBottom < 200) {
      bottom.scrollIntoView({ behavior: "smooth", block: "end" });
    }
  }, [messages]);

  const toggleReference = (id: string) => {
    setExpandedRefs(prev => {
      const newSet = new Set(prev);
      if (newSet.has(id)) {
        newSet.delete(id);
      } else {
        newSet.add(id);
      }
      return newSet;
    });
  };

  return (
    <div className="relative flex flex-col h-full w-full backdrop-blur-md rounded-2xl border shadow-sm overflow-hidden transition-all duration-700 ease-in-out" style={{ backgroundColor: colors.black90, borderColor: colors.border }}>
      <div className="p-4 border-b flex items-center justify-between" style={{ borderColor: colors.border }}>
        <span
          className="text-xs font-mono uppercase tracking-widest"
          style={{ color: colors.textLight }}
        >
          Live Transcript
        </span>
        <button
          type="button"
          title="Transcript disclaimer"
          aria-label="Transcript disclaimer"
          onClick={() => setShowDisclaimer((prev) => !prev)}
          className="text-[10px] font-mono uppercase tracking-wide transition-colors hover:opacity-80"
          style={{ color: colors.textLight }}
        >
          Notice
        </button>
      </div>

      {showDisclaimer && (
        <div className="absolute top-14 right-4 z-30 w-80 max-w-[calc(100%-2rem)] backdrop-blur-md border rounded-lg p-3 shadow-lg" style={{ backgroundColor: colors.black95, borderColor: colors.border }}>
          <div className="flex items-center justify-between">
            <h3 className="text-xs font-semibold uppercase tracking-wide" style={{ color: colors.textPrimary }}>Notice</h3>
            <button
              type="button"
              onClick={() => setShowDisclaimer(false)}
              className="hover:opacity-80"
              style={{ color: colors.textLight }}
              aria-label="Close disclaimer"
            >
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
          <div className="mt-2 border-t pt-3" style={{ borderColor: colors.border }}>
          <p className="text-xs leading-relaxed" style={{ color: colors.textTranscript }}>
            Moshi text is generated by the Moshi model, and user text is predicted by a streaming ASR model.
            Since the conversation is full-duplex, it does not follow the traditional turn-based structure.
            To improve readability, we organize the content spoken by Moshi and user into turns with voice-activity-based heuristics.
            Therefore, the transcript may contain some unnatural turn breaks.
            These errors, however, do not reflect the actual conversation flow and do not affect the full-duplex human-machine interaction.
          </p>
          </div>
        </div>
      )}

      <div ref={scrollContainerRef} className="flex-1 overflow-y-auto p-4 space-y-6">
        {messages.length === 0 ? (
          <div className="flex items-center justify-center h-full text-sm italic" style={{ color: colors.textDisabled }}>
            Waiting for conversation...
          </div>
        ) : (
          messages.map((msg) => (
            <div
              key={msg.id}
              className={`flex flex-col ${msg.role === 'user' ? 'items-end' : 'items-start'}`}
            >
              <span
                className="text-xs font-mono mb-1 uppercase"
                style={{ color: msg.role === "user" ? colors.textLight : colors.accentGreen }}
              >
                {msg.role === 'user' ? 'You' : 'Moshi'}
              </span>
              <div
                className={`max-w-[90%] rounded-2xl p-3 text-sm leading-relaxed shadow-sm ${msg.role === 'user' ? 'rounded-tr-none' : 'rounded-tl-none'}`}
                style={
                  msg.role === "user"
                    ? { backgroundColor: colors.bgPanel, color: colors.textTranscript }
                    : { backgroundColor: colors.black, border: `1px solid ${colors.border}`, color: colors.textTranscript }
                }
              >
                <div>{msg.text.trim()}</div>

                {/* Reference Section */}
                {msg.referenceText && (
                  <div className="mt-2 min-w-0">
                    <button
                      type="button"
                      onClick={() => toggleReference(msg.id)}
                      className="flex items-center gap-1.5 text-xs font-medium px-2 py-1 -ml-2 rounded transition-colors"
                      style={{ color: colors.accentBlue }}
                    >
                      <svg className={`w-3 h-3 transition-transform shrink-0 ${expandedRefs.has(msg.id) ? 'rotate-90' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                      </svg>
                      {expandedRefs.has(msg.id) ? 'Hide Reference' : 'View Reference'}
                    </button>

                    {expandedRefs.has(msg.id) && (
                      <div
                        className="mt-2 pt-2 border-t text-xs font-mono whitespace-pre-wrap leading-relaxed max-h-60 overflow-y-auto"
                        style={{ color: colors.textLight, borderTopColor: colors.border }}
                      >
                        {msg.referenceLmLabel ? (
                          <div className="mb-2 text-[12px] leading-tight text-left opacity-90" style={{ color: colors.textLight }}>
                            {msg.referenceLmLabel}
                          </div>
                        ) : null}
                        {msg.referenceText?.trim()}
                      </div>
                    )}
                  </div>
                )}
              </div>
            </div>
          ))
        )}
        <div ref={bottomRef} />
      </div>
    </div>
  );
};

export default TranscriptionPanel;
